name: $pluginName
main: $pluginMain
depend: [ Kotlin ]
api-version: '1.16'
author: $author
version: $version
commands:
  dashify:
    usage: /<dashify> <password | port> <password here | port here>
    description: Dashboard for Minecraft